services:
  postgres:
    image: postgres:15
    container_name: postgres_iu6
    restart: unless-stopped

    environment:
      POSTGRES_DB: iu6
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
